apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: {{NAMESPACE}}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 9000
    protocol: TCP
  selector:
    app: auth
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: auth
        app: auth
    spec:
      containers:
      - name: main
        image: nipun/klusterfuck-authproxy:0.2.1
        ports:
        - containerPort: 9000
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: auth
  namespace: {{NAMESPACE}}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{NAMESPACE}}.kube.local
    http:
      paths:
      - path: /auth/
        backend:
          serviceName: auth
          servicePort: 80
