apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: {{NAMESPACE}}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 9000
    protocol: TCP
  selector:
    app: auth
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: auth
        app: auth
    spec:
      containers:
      - name: main
        image: klusterfuck/authproxy:{{TAG}}
        env:
          - name: KEYCLOAK_URL
            value: {{KEYCLOAK_URL}}
          - name: REALM
            value: {{REALM}}
          - name: CLIENT_ID
            value: {{CLIENT_ID}}
        ports:
        - containerPort: 9000
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 200m
            memory: 100Mi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: auth
  namespace: {{NAMESPACE}}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{NAMESPACE}}.{{DOMAIN}}
    http:
      paths:
      - path: /auth/
        backend:
          serviceName: auth
          servicePort: 80
