apiVersion: v1
kind: ReplicationController
metadata:
  name: cloud9
  namespace: {{NAMESPACE}}
  labels:
    component: cloud9
spec:
  replicas: 1
  selector:
    app: cloud9
    component: cloud9
  template:
    metadata:
      labels:
        app: cloud9
        component: cloud9
    spec:
      containers:
      - name: cloud9
        image: kdelfour/cloud9-docker
        ports:
          - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cloud9
  namespace: {{NAMESPACE}}
  labels:
    app: cloud9
    component: cloud9
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: cloud9
    component: cloud9
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cloud9
  namespace: {{NAMESPACE}}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    "ingress.kubernetes.io/auth-url": "http://auth.{{NAMESPACE}}.svc.cluster.local/"
    "ingress.kubernetes.io/auth-signin": "http://cloud9.{{NAMESPACE}}.{{DOMAIN}}/auth/signin.html?redirect=../"
spec:
  rules:
  - host: cloud9.{{NAMESPACE}}.{{DOMAIN}}
    http:
      paths:
      - path: /
        backend:
          serviceName: cloud9
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cloud9-auth
  namespace: {{NAMESPACE}}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: cloud9.{{NAMESPACE}}.{{DOMAIN}}
    http:
      paths:
      - path: /auth/
        backend:
          serviceName: auth
          servicePort: 80
