apiVersion: v1
kind: Service
metadata:
  name: {{NAME}}
  namespace: {{NAMESPACE}}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: {{NAME}}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{NAME}}
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{NAME}}
        app: {{NAME}}
    spec:
      containers:
      - name: main
        image: {{IMAGE}}
        env:
          - name: WORK_DIR
            value: {{WORK_DIR}}
          - name: GIT_URL
            value: {{GIT_URL}}
          - name: GIT_USER
            value: {{GIT_USER}}
          - name: GIT_PASSWORD
            value: {{GIT_PASSWORD}}
          - name: GIT_COMMIT
            value: {{GIT_COMMIT}}
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{NAME}}
  namespace: {{NAMESPACE}}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    "ingress.kubernetes.io/auth-url": "http://auth.{{NAMESPACE}}.svc.cluster.local/"
    "ingress.kubernetes.io/auth-signin": "http://{{NAMESPACE}}.{{DOMAIN}}/auth/signin.html"
spec:
  rules:
  - host: {{NAMESPACE}}.{{DOMAIN}}
    http:
      paths:
      - path: /{{NAME}}/
        backend:
          serviceName: {{NAME}}
          servicePort: 80
