kind: Namespace
apiVersion: v1
metadata:
  name: klusterfuck
  labels:
    name: klusterfuck
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: klusterfuck
  namespace: klusterfuck
  labels:
    component: klusterfuck
spec:
  replicas: 1
  selector:
    app: klusterfuck
    component: klusterfuck
  template:
    metadata:
      labels:
        app: klusterfuck
        component: klusterfuck
    spec:
      containers:
      - name: klusterfuck
        securityContext:
          privileged: true
        image: klusterfuck/admin:0.3.0
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8080
            scheme: HTTP
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: "KEYCLOAK_URL"
            value: "http://keycloak.klusterfuck.svc.cluster.local/auth"
          - name: "KEYCLOAK_REALM"
            value: "master"
          - name: "KEYCLOAK_CLIENT_ID"
            value: "klusterfuck"
          - name: KEYCLOAK_ADMIN_USER
            value: "admin"
          - name: KEYCLOAK_ADMIN_PASSWORD
            value: "admin"
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: keycloak
  namespace: klusterfuck
  labels:
    component: keycloak
spec:
  replicas: 1
  selector:
    app: keycloak
    component: keycloak
  template:
    metadata:
      labels:
        app: keycloak
        component: keycloak
    spec:
      containers:
      - name: keycloak
        image: jboss/keycloak:3.1.0.Final
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /auth
            port: 8080
            scheme: HTTP
        env:
          - name: KEYCLOAK_USER
            value: "admin"
          - name: KEYCLOAK_PASSWORD
            value: "admin"
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 1000m
            memory: 1000Mi
---
apiVersion: v1
kind: Service
metadata:
  name: klusterfuck
  namespace: klusterfuck
  labels:
    app: klusterfuck
    component: klusterfuck
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: klusterfuck
    component: klusterfuck
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: klusterfuck
  labels:
    app: keycloak
    component: keycloak
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: keycloak
    component: keycloak
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: klusterfuck
  namespace: klusterfuck
spec:
  rules:
  - host: klusterfuck.kube.local
    http:
      paths:
      - path: /
        backend:
          serviceName: klusterfuck
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak
  namespace: klusterfuck
spec:
  rules:
  - host: keycloak.kube.local
    http:
      paths:
      - path: /
        backend:
          serviceName: keycloak
          servicePort: 80
