kind: Namespace
apiVersion: v1
metadata:
  name: klusterfuck
  labels:
    name: klusterfuck
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kf-admin
  namespace: klusterfuck
subjects:
- kind: ServiceAccount
  name: default
  namespace: klusterfuck
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: klusterfuck
  namespace: klusterfuck
  labels:
    component: klusterfuck
spec:
  replicas: 1
  selector:
    app: klusterfuck
    component: klusterfuck
  template:
    metadata:
      labels:
        app: klusterfuck
        component: klusterfuck
    spec:
      containers:
      - name: klusterfuck
        securityContext:
          privileged: true
        image: nipun/klusterfuck-admin:0.2.1
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8080
            scheme: HTTP
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: GOGS_URL
            value: "gogs.klusterfuck.svc.cluster.local"
          - name: GOGS_USER
            value: "gogsadmin"
          - name: GOGS_PASSWORD
            value: "admin1234"
          - name: AGENT_IMAGE
            value: "nipun/klusterfuck-agent:0.2.1"
          - name: FLOW_IMAGE
            value: "nipun/klusterfuck-flow:0.2.1"
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: 800m
            memory: 1000Mi
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: gogs
  namespace: klusterfuck
  labels:
    component: gogs
spec:
  replicas: 1
  selector:
    app: gogs
    component: gogs
  template:
    metadata:
      labels:
        app: gogs
        component: gogs
    spec:
      containers:
      - name: gogs
        image: fabric8/gogs
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
        env:
          - name: ADMIN_USER_NAME
            value: "gogsadmin"
          - name: ADMIN_USER_PASSWORD
            value: "admin1234"
          - name: DOMAIN
            value: "klusterfuck.svc.cluster.local"
        ports:
          - containerPort: 3000
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: klusterfuck
  namespace: klusterfuck
  labels:
    app: klusterfuck
    component: klusterfuck
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: klusterfuck
    component: klusterfuck
---
apiVersion: v1
kind: Service
metadata:
  name: gogs
  namespace: klusterfuck
  labels:
    app: gogs
    component: gogs
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: gogs
    component: gogs

