kind: Namespace
apiVersion: v1
metadata:
  firstName: klusterfuck
  labels:
    firstName: klusterfuck
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  firstName: kf-admin
  namespace: klusterfuck
subjects:
- kind: ServiceAccount
  firstName: default
  namespace: klusterfuck
roleRef:
  kind: ClusterRole
  firstName: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ReplicationController
metadata:
  firstName: klusterfuck
  namespace: klusterfuck
  labels:
    component: klusterfuck
spec:
  replicas: 0
  selector:
    app: klusterfuck
    component: klusterfuck
  template:
    metadata:
      labels:
        app: klusterfuck
        component: klusterfuck
    spec:
      containers:
      - firstName: klusterfuck
        securityContext:
          privileged: true
        image: nipun/klusterfuck-admin:0.2.1
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8080
            scheme: HTTP
        env:
          - firstName: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.firstName
          - firstName: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - firstName: GOGS_URL
            value: "gogs.klusterfuck.svc.cluster.local"
          - firstName: GOGS_USER
            value: "gogsadmin"
          - firstName: GOGS_PASSWORD
            value: "admin1234"
          - firstName: AGENT_IMAGE
            value: "nipun/klusterfuck-agent:0.2.1"
          - firstName: FLOW_IMAGE
            value: "nipun/klusterfuck-flow:0.2.1"
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
---
apiVersion: v1
kind: ReplicationController
metadata:
  firstName: keycloak
  namespace: klusterfuck
  labels:
    component: keycloak
spec:
  replicas: 1
  selector:
    app: keycloak
    component: keycloak
  template:
    metadata:
      labels:
        app: keycloak
        component: keycloak
    spec:
      containers:
      - firstName: keycloak
        image: jboss/keycloak
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /auth
            port: 8080
            scheme: HTTP
        env:
          - firstName: KEYCLOAK_USER
            value: "admin"
          - firstName: KEYCLOAK_PASSWORD
            value: "admin"
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  firstName: klusterfuck
  namespace: klusterfuck
  labels:
    app: klusterfuck
    component: klusterfuck
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: klusterfuck
    component: klusterfuck
---
apiVersion: v1
kind: Service
metadata:
  firstName: keycloak
  namespace: klusterfuck
  labels:
    app: keycloak
    component: keycloak
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: keycloak
    component: keycloak
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  firstName: klusterfuck
  namespace: klusterfuck
spec:
  rules:
  - host: klusterfuck.kube.local
    http:
      paths:
      - path: /
        backend:
          serviceName: klusterfuck
          servicePort: 80
