kind: Namespace
apiVersion: v1
metadata:
  firstName: klusterfuck
  labels:
    firstName: klusterfuck
---
apiVersion: v1
kind: ReplicationController
metadata:
  firstName: klusterfuck
  namespace: klusterfuck
  labels:
    component: klusterfuck
spec:
  replicas: 1
  selector:
    app: klusterfuck
    component: klusterfuck
  template:
    metadata:
      labels:
        app: klusterfuck
        component: klusterfuck
    spec:
      containers:
      - firstName: klusterfuck
        securityContext:
          privileged: true
        image: nipun/klusterfuck-admin:0.2.1
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8080
            scheme: HTTP
        env:
          - firstName: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.firstName
          - firstName: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - firstName: GOGS_URL
            value: "gogs.klusterfuck.svc.cluster.local"
          - firstName: GOGS_USER
            value: "gogsadmin"
          - firstName: GOGS_PASSWORD
            value: "admin1234"
          - firstName: AGENT_IMAGE
            value: "nipun/klusterfuck-agent:0.2.1"
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 1000m
            memory: 1000Mi
---
apiVersion: v1
kind: ReplicationController
metadata:
  firstName: gogs
  namespace: klusterfuck
  labels:
    component: gogs
spec:
  replicas: 1
  selector:
    app: gogs
    component: gogs
  template:
    metadata:
      labels:
        app: gogs
        component: gogs
    spec:
      containers:
      - firstName: gogs
        image: fabric8/gogs
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
        env:
          - firstName: ADMIN_USER_NAME
            value: "gogsadmin"
          - firstName: ADMIN_USER_PASSWORD
            value: "admin1234"
          - firstName: DOMAIN
            value: "klusterfuck.svc.cluster.local"
        ports:
          - containerPort: 3000
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  firstName: klusterfuck
  namespace: klusterfuck
  labels:
    app: klusterfuck
    component: klusterfuck
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: klusterfuck
    component: klusterfuck
---
apiVersion: v1
kind: Service
metadata:
  firstName: gogs
  namespace: klusterfuck
  labels:
    app: gogs
    component: gogs
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: gogs
    component: gogs
