kind: Namespace
apiVersion: v1
metadata:
  name: gogs
  labels:
    name: gogs
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: gogs
  namespace: gogs
  labels:
    component: gogs
spec:
  replicas: 1
  selector:
    app: gogs
    component: gogs
  template:
    metadata:
      labels:
        app: gogs
        component: gogs
    spec:
      containers:
      - name: gogs
        image: fabric8/gogs
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        # use downward API
        env:
          - name: ADMIN_USER_NAME
            value: "gogsadmin"
          - name: ADMIN_USER_PASSWORD
            value: "admin"
          - name: DOMAIN
            value: "gogs.kube.local"
        ports:
          - containerPort: 3000
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gogs
  namespace: gogs
  labels:
    app: gogs
    component: gogs
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: gogs
    component: gogs
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gogs
  namespace: gogs
spec:
  rules:
  - host: gogs.kube.local
    http:
      paths:
      - path: /
        backend:
          serviceName: gogs
          servicePort: 3000
