spring:
  datasource:
#    url: ${DB_URL:jdbc:mysql://localhost:3306/klusterfuck}
    url: ${DB_URL:jdbc:derby:./data/klusterfuck;create=true}
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

app:
  env: dev
  kube:
    configType: kubeconf
    namespace: ${NAMESPACE}
    agentImage: ${AGENT_IMAGE}
    flowImage: ${FLOW_IMAGE}
  adminUser: ${ADMIN_USER:}
  adminPassword: ${ADMIN_PASSWORD:}
  keycloak:
    adminUser: admin
    adminPassword: admin

keycloak:
  auth-server-url: "http://keycloak.klusterfuck.svc.cluster.local/auth"
  realm: "master"
  public-client: false
  resource: "klusterfuck"
  principal-attribute: "preferred_username"
