spring:
  datasource:
#    url: ${DB_URL:jdbc:mysql://localhost:3306/klusterfuck}
    url: ${DB_URL:jdbc:derby:./data/klusterfuck;create=true}
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

app:
  env: dev
  kube:
    configType: kubeconf
    agentImage: ${AGENT_IMAGE}
    flowImage: ${FLOW_IMAGE}
  keycloak:
    adminUser: ${KEYCLOAK_ADMIN_USER}
    adminPassword: ${KEYCLOAK_ADMIN_PASSWORD}

keycloak:
  auth-server-url: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM}
  public-client: false
  resource: ${KEYCLOAK_CLIENT_ID}
  principal-attribute: "preferred_username"
