spring:
  datasource:
#    url: ${DB_URL:jdbc:mysql://localhost:3306/klusterfuck}
    url: ${DB_URL:jdbc:derby:/app/db/klusterfuck;create=true}
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

app:
  env: prod
  domain: ${DOMAIN:kube.local}
  kube:
    configType: env
    flowImage: "klusterfuck/flow"
    authProxyImage: "klusterfuck/authproxy"
    imageVersion: ${image.version}
  keycloak:
    clusterInternalUrl: ${KEYCLOAK_INTERNAL_URL:http://keycloak.klusterfuck.svc.cluster.local/auth}
    adminUser: ${KEYCLOAK_ADMIN_USER:admin}
    adminPassword: ${KEYCLOAK_ADMIN_PASSWORD:admin}

keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://keycloak.klusterfuck.svc.cluster.local/auth}
  realm: ${KEYCLOAK_REALM:master}
  public-client: false
  resource: ${KEYCLOAK_CLIENT_ID:klusterfuck}
  principal-attribute: "preferred_username"
